project:
  type: website
website:
  title: "Kenny's Website"
  site-url: https://kennyweichen.com
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts.qmd
format:
  html:
    css: styles.css
    include-in-header:
      - text: |
          <script src="/custom.js"></script>